openapi: "3.0.0"

# スキーマの情報
info:
  title: Reminder API Document
  version: "0.0.1"
  description: Reminder API のドキュメント

# サーバ情報
servers:
  - url: http://localhost:8080

# エンドポイント
paths:
  /reminders:
    get:
      responses:
        "200":
          description: OK

# 再利用可能なスキーマ定義
components:
  schemas:
    ReminderDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        dueDate:
          type: string
          format: date
        priority:
          type: integer
        isCompleted:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
